name: Secert And SSH Actions Demo
on: [push]
jobs:
  secert-ssh-jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: login ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true #当发生错误时停止继续执行
          script: |
            pwd
            ls -l
            touch userName.txt
            echo ${{secrets.USERNAME}} >> userName.txt