name: Tag Test
on:
  push:
    tags:
      - v*.*.*

jobs: 
  test-tags: 
    runs-on: ubuntu-latest
    # github.sha 就是commitid信息
    steps: 
      - uses: actions/checkout@v2
      - name: Test github context info
        run: 
         echo ${{github.ref}}
         echo ${{github.ref_name}}
         echo ${{github.sha}}
      # 查找替换{{tags}} https://github.com/marketplace/actions/find-and-replace
      # github 打tag的步骤
      # 1. git add .
      # 2. git commit -m 'xxxxx'
      # 3. git tag -a v0.0.3 -m 'version 0.0.3' 
      # 4. git push --tags
      # 5. git push
      - name: Find and replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
         find: "{{tag}}"
         replace: "${{github.ref_name}}"
         include: "docker-compose-online.yml" 
      - run: cat docker-compose-online.yml
        